Nome = input('Digite algo:\n')
print('O tipo primitivo desse valor é',type(Nome))
print('É alfanumérico?' ,Nome.isalnum())
print('É uma letra?' ,Nome.isalpha())
print('É maiúscula?' ,Nome.isupper())
print('Está captalizado? ',Nome.istitle())
print('É minuscula?' ,Nome.islower())
print('É um número?' ,Nome.isnumeric())
print('Só tem espaços?'.format(Nome).isspace())
