nome = input (' qual é o seu nome: ')
altura = input (' qual é a sua altura: ')
peso = input (' qual é o seu peso: ')
idade = input (' qual é a sua idade: ')
print ( nome, 'você vai ser rico! ',altura,' você já pode parar de crescer né! ', peso, nome,' você faz academia?,porque posso sentir sua força ',idade,' ta bem conservado hein! ')
dia = input (' em que dia você nasceu: ')
mês=input(' em que mês você nasceu: ')
ano=input('em que ano você nasceu:')
print (' eu gostei muito desse dia, ', dia, mês, ano,' foi muito divertido ')